### ISSUE TITLE
Do the unblock rules need a priority parameter?

### ISSUE THREAD

**Issue by ryanlrussell** [SDNC2/PhantomFloodlight#3]
Floodlight App 0.0.1

(This one I ask completely out of ignorance and assumption. If I'm just thinking about it wrong, then please disregard and close.)

I see a number of unblock actions take a priority field. This matches the block actions. I can certainly see where priority makes sense for block, but is it useful on unblock? If you are unblocking (for example) arp, would you not remove the arp block for the mac address at any priority? Or put another way, can a single mac address be blocked for arp more than once, at different priorities, at the same time? And if it is, does it make sense to remove it at one priority, and leave it at another? Or alternately, do you want to only unblock if it was blocked at a specified priority, and fail otherwise?

**Comment by rsharo** [comment]
### BLUF

@ryanlrussell Unfortunately the priority field must remain: it resolves "overlaps" in firewall rules.

### Longer answer...

When activated, Floodlight's firewall automatically blocks _all_ traffic by default.  This means "unblock ip" is more than just the inverse of "block ip" -- "unblock ip" actually adds a firewall rule that allows traffic to flow.  So you can actually have block (aka, "deny") and unblock (aka "allow") rules in the same list at the same time.

So you may be wondering... what happens if two firewall rules conflict?  Suppose I install a "deny" rule against the entire subnet 10.0.0.0/8 and an "allow" rule against the single IP 10.0.0.1?  The priority field determines which rule takes precedence.

I've tried to include support for "undo" operations from the Phantom UI in spite of this.  If you click "undo" on a "block ip" instruction, then it will call "unblock ip" with the same parameters as were passed to the "block" action.  This means that, if the deny rule had a priority of 100, then clicking "undo" will delete that deny rule and insert an allow rule with the same priority: 100 in this case.  If priority is left unspecified, it will be taken as zero.

Hope this helps!

Closing the issue for now but feel free to reply if more info is needed.
